version: "3"
services:
  mariadb:
    container_name: prestashop_db
    image: mariadb
    restart: unless-stopped
    networks:
      - prestashop_net
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE

  prestashop:
    container_name: prestashop_dev
    build: .
    restart: unless-stopped
    networks:
      - prestashop_net
    ports:
      - 3000:80
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      - ./src:/var/www/html
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PS_DEV_MODE
      - DB_SERVER
      - DB_USER
      - DB_PASSWD
      - DB_NAME
      - PS_INSTALL_AUTO

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prestashop_db_manager
    restart: unless-stopped
    networks:
      - prestashop_net
    links:
      - mariadb:mariadb
    ports:
      - 1234:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST
      - PMA_USER
      - PMA_PASSWORD

networks:
  prestashop_net: